apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  MONGODB_PASSWORD: MONGODB_PASSWORD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7
          ports:
            - containerPort: 27017
              name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGODB_PASSWORD
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: mongodb-data
          hostPath:
            path: /data/renqing-mongodb
            type: DirectoryOrCreate
